export const Products = [
  {
    id: 1,
    title: "iPhone 9",
    description: "An apple mobile which is nothing like apple",
    price: 549,
    discountPercentage: 12.96,
    rating: 4.69,
    stock: 94,
    quantity : 1 ,
    brand: "Apple",
    category: "smartphones",
    thumbnail: "/media/thumbnail1.jpg",
    images: ["/media/img1.jpg"]},
   {
     id: 2,
     quantity : 1,
     title: "iPhone X",
     description:
       "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
     price: 899,
     discountPercentage: 17.94,
     rating: 4.44,
     stock: 34,
     brand: "Apple",
     category: "smartphones",
     thumbnail: "/media/thumbnail2.jpg",
     images: [
      "/media/img2.jpg"],
   },
   {
     id: 3,
     title: "Samsung Universe 9",
     quantity : 1 ,
     description:
       "Samsung's new variant which goes beyond Galaxy to the Universe",
     price: 1249,
     discountPercentage: 15.46,
     rating: 4.09,
     stock: 36,
     brand: "Samsung",
     category: "smartphones",
     thumbnail: "/media/thumbnail3.jpg",
     images: ["/media/img3.jpg"]
   },
   {
     id: 4,
     quantity : 1,
     title: "OPPOF19",
     description: "OPPO F19 is officially announced on April 2021.",
     price: 280,
     discountPercentage: 17.91,
     rating: 4.3,
     stock: 123,
     brand: "OPPO",
     category: "smartphones",
     thumbnail: "/media/thumbnail4.jpg",
     images: ["/media/img4.jpg"
     ],
   },
   {
     id: 5,
     title: "Huawei P30",
     quantity : 1 ,
     description:
       "Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
     price: 499,
     discountPercentage: 10.58,
     rating: 4.09,
     stock: 32,
     brand: "Huawei",
     category: "smartphones",
     thumbnail: "/media/thumbnail5.jpg",
     images: [ "/media/img5.jpg"
     ],
   },
   {
     id: 6,
     quantity : 1,
     title: "MacBook Pro",
     description:
       "MacBook Pro 2021 with mini-LED display may launch between September, November",
     price: 1749,
     discountPercentage: 11.02,
     rating: 4.57,
     stock: 83,
     brand: "Apple",
     category: "laptops",
     thumbnail: "/media/thumbnail6.png",
     images: ["/media/img6.jpg"],
   },
   {
     id: 7,
     title: "Samsung Galaxy Book",
     quantity : 1 ,
     description:
       "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
     price: 1499,
     discountPercentage: 4.15,
     rating: 4.25,
     stock: 50,
     brand: "Samsung",
     category: "laptops",
     thumbnail: "/media/thumbnail7.jpg",
     images: ["/media/img7.jpg"
     ],
   
    }]